### ISSUE TITLE
IPyConsole 1.2 doesnt open on Ubuntu 14.04

### ISSUE THREAD

**Issue by spaceof7** [elpaso/qgis-ipythonconsole#5]
I have QGIS 2.8.3 installed from the LTR-nightly repository.  IPyConsole used to work correctly but now I get an error message telling me the that the Ipython version needs to be 3.1 or greater.  If I downgrade to the 1.1 plugin version then the console launches properly.  I am using ipython/ipython-qtconsole installed from apt, which is version 1.2.1-2.  If I try to install ipython via pip then IPyConsole give me the error "cannot import name IPythonWidget".

**Comment by femtomatic** [comment]
Hi,
I have QGIS 2.10 installed from the AUR on Archlinux and have the same error. The error is actually on line 211 in *IPyConsole.py*, the `import` statement is wrong, there is no module named `IPythonWidget` in `IPython.qt.console.rich_ipython_widget`. The error message is misleading because the try statement is too long.
I changed line 211 in *IPyConsole.py* to:
```python
from IPython.qt.console.rich_ipython_widget import RichIPythonWidget
```
and line 256 to:
```python
class myWidget(RichIPythonWidget):
```
now everything works.

Cheers!

**Comment by elpaso** [comment]
I've just released a new version which fixes another problem, can you please test it and if it doesn't work you can maybe add a conditional instruction to check for IPython version and apply your patches in a PR?

Thanks.

**Comment by jesswren** [comment]
I am still having this problem in QGIS 2.18.19, on Debian Sid.  My ipython version is 5.5.0 and my python version is 2.7.15.
